server:
  port: 8080
spring:
  application:
    name: consumer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  #    ip-address: 172.16.192.135
  client:
    serviceUrl:
      defaultZone: ${registry.url}