server:
  port: 9070
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  #    ip-address: 172.16.192.135
  client:
    serviceUrl:
      defaultZone: ${register.url:http://172.16.34.156:9090/eureka/}
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

resilience4j:
  circuitbreaker:
    backends:
      circuitA: # ＃断路器名
        truering-buffer-size-in-closed-state: 5 ＃环形缓冲区是在封闭状态下使用的大小
        ring-buffer-size-in-half-open-state: 3 # HalfOpen 状态下的大小
        wait-duration-in-open-state: 5000 # Open持续时间
        failure-rate-threshold: 50 # 到打开状态的阈值
        record-failure-predicate: com.example.resilience.RecordFailurePredicate
#        ignore-exceptions: #没有失败＃异常类和计数
#          - com.example.resilience.exception.BusinessException
#        record-exceptions: ＃异常类失败和计数
#          - com.example.resilience.exception.SystemException